### ISSUE TITLE
Component Color Audit of Default Theme 

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#203]
**Background**

We need to take a look at components to see what colors are currently being used to cull them down to a succinct list to make sure values are consistent. 

- pull color values for different states and colors of components 
- states priority list can be found here: border color, background color, text color, all states (hover, disabled, interaction) 

The fixes for this will live in the uplift theme. 

**UI Uplift Steps:**

- [x] audit
- [x] color palette for uplift theme TIMING: mid Nov, dev implementation mid Feb
- [x] color audit of components (this ticket) (non-structural changes) 
  - encompassing styling ie: disable/active/etc
  - consolidate colors being used in soho 
  - redefine values in properties 
  - auditing properties code
  - updating uplift theme code based on findings ie: font color the same as disable button color, need to change 
- [ ] audit for structural changes of components TIMING: end Feb, dev implementation end of April
  - fonts, boarders, sizing, type, spacing, etc (in ticket: #222 )

**Comment by stephanie-ui-travis-perkins** [comment]
When completing the above work will this include ensuring that the Infor SoHo guidelines are compliant with WCAG 2.1 AA compliance? Will this address the issues with the alert colours against the white and light grey backgrounds, which are currently not a complaint?

**Comment by kayiuho** [comment]
@stephanie-ui-travis-perkins This issue is not directly related to accessibility. For Default and Dark themes, the color values have not changed and they are still using the same color palette from previous SoHo. However, we have updated our High Contrast theme to pass WCAG 2.1 AAA standards. The High Contrast theme now comes with 4 new color values for the different statuses (alert colors): caution, danger, success, and warning. You may see them in the design tokens [here].(https://github.com/infor-design/design-system/blob/4e8217088b7da7a7f15d92c614ea44ebfb73cac4/design-tokens/theme-soho/variants/contrast/theme.json#L4)

Please also note the [Accessibility Guidelines](https://design.infor.com/guidelines/identity/colors) on the Infor Design System website recommends that "Colors must not be used alone to indicate a status, they always must be used in conjunction with an icon or text to secondarily describe the color meaning."

If you have any further support questions or requests, please create a new issue for the IDS team to address. Thanks!

**Comment by kayiuho** [comment]
@nickwynja @clepore This is the "scratchpad" I shared yesterday plus the initial findings - let me know if you need more clarification.

![component_color_audit_basic_controls_20181025](https://user-images.githubusercontent.com/34747859/47512246-ca1e5d80-d849-11e8-9af9-bc53d68e7df2.jpg)

![component_color_audit_initial_findings_20181025](https://user-images.githubusercontent.com/34747859/47512253-cdb1e480-d849-11e8-9837-b820482e9366.png)
