### ISSUE TITLE
Add Button Position Standards to Modal/Form Pages

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#216]
This came up on Ms teams chat and has been mentioned in the past several times. Teams would like to see standards on the site on placement of form and modal buttons.

In the past we came up with the standard that the primary button is on the right. As per http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right so this is what we had settled on in the past.

Also to note:
- windows standard is primary on the left
- mac standard is primary on the right
https://ux.stackexchange.com/questions/1072/ok-cancel-on-left-right

So, one suggestion is it might be an idea to switch the placement based on the platform. If this can be automated.

Task
- add a note on the to the forms code page and design page
- add a note on the to the modal code page and design page

**Comment by kayiuho** [comment]
We may also consider adding more guidelines around the general use of actions/buttons (related issue: #121) while we enhance guidelines on button placement on modals.

**Comment by kayiuho** [comment]
@tmcconechy I'm assuming that a majority of Infor's cloud users are on Windows (maybe up to 85-90%)? I don't see why it'd be a bad idea to switch the placement of the primary and secondary buttons based on the platform. However, our modal component already comes with the definition of "Secondary | Primary" actions. If there's no complaint about users failing to complete their tasks using that definition, then how much effort does it worth to implement the "platform switch"? 

From my UX research, the order of buttons in modals, "Primary | Secondary" or "Secondary | Primary", are both reasonable choices, with one study stating that modal with Primary action last improves the workflow because a "dialog box" ends with a conclusion, which is what our current definition is for modals.

In terms of button actions on a form.. if buttons are being placed near the input fields (on the bottom of the page) then having "Primary | Secondary" buttons to the bottom left of the form would be the most reasonable choice. Based on the reading comprehension of left to right, having left-aligned buttons to the above form would help users to stay focused to complete the tasks as their eyes are already fixated to the left and there's less distance to travel to find the clear path to completion. 

I'll be adding the button placement guidelines to the [Forms page](https://design.infor.com/guidelines/patterns/forms), and I've added button placement guidelines to the [Modals page](https://design.infor.com/guidelines/patterns/modals).

**Comment by tmcconechy** [comment]
hi @kayiuho 
If we did change the order on platform it would probably only be a (1) or (2) small ticket, i think it could be worth putting in the backlog then.

Aside from that i agree with everything you said except I'm not sure if it makes sense to change the order based on if its a modal or a form? Shouldn't it be the same on both whatever we choose as the default (sounds like Secondary | Primary)?

Not even here in github the primary is to the right (form).

**Comment by kayiuho** [comment]
We could backlog the "Windows/Mac switcher" but I'm still reserved about the need for it without any user data/testing. It could also confuse the users who have been using the software for a long time, if we decide to flip it (so Window users will be seeing "Save", "Submit", etc on the left just because they're on Windows).

Aligning button actions to the bottom left on forms don't necessary need to be consistent with the modal buttons, since the workflow is different and they require different solutions to guide the users down a clear path.

For the github case here, note that the buttons are placed within a container (fixed width), similar to a modal or a card. If there were outside of the container, I don't know if the design would be done the same as it is now.

**Comment by tmcconechy** [comment]
I think i would make it as an option that it switched so it wouldnt just do it for everyone unless they wanted. 

I guess as long as we document the reasons we should be ok, i can just see someone asking about it being different in different cases and getting confused and thinking its an issue. But i didnt do the research other than seeing what your saying that its debatable either way.

**Comment by kayiuho** [comment]
Button placement guidelines are updated in:
https://design.infor.com/guidelines/patterns/forms
https://design.infor.com/guidelines/patterns/modals

Closing this issue.
