### ISSUE TITLE
Design review for drilldown pattern

### ISSUE THREAD

**Issue by scott-newman-infor** [infor-design/design-system#217]
We have developed a drilldown table experience and could use some advice polishing it up:

Parent screen:
![screen shot 2018-10-24 at 9 53 13 am](https://user-images.githubusercontent.com/42583078/47436189-01223f80-d774-11e8-8b79-fd90ad5bfc3a.png)

Drilled down:
![screen shot 2018-10-24 at 9 53 25 am](https://user-images.githubusercontent.com/42583078/47436190-01223f80-d774-11e8-9b85-b684c24fcf58.png)

Some issues for starters:

1. The back/next buttons in the header look exactly like the "drill-in" and "drill-back" icons respectively.    These buttons are meant to navigate amongst the items in the parent table.   Users find it confusing that the same icon is used.  Do you have a better way to depict this?
2. Along the same lines, the back/next buttons clash with the other header buttons (Approve and Cancel).  It's awkward to page back and next and have these buttons jump around as the other action buttons may appear or not appear based on permission (i.e. some Projects don't have Approve buttons).  If we right justify the back/next buttons, then we'll have a problem when there exists a spillover more "..." menu.  Perhaps the back/next buttons don't even belong on this bar but we are not sure where else to put them.

Thanks for your time.

**Comment by scott-newman-infor** [comment]
I should add that this experience will be repeated in our product suite potentially dozens of times, so getting it right is paramount.  

There was once a "Step Process" control in Soho but it seems to have lost favor.  I bring it up because it actually had an answer as to placement of the back/next buttons:

<img width="946" alt="screen shot 2018-11-08 at 9 53 50 am" src="https://user-images.githubusercontent.com/42583078/48206468-7ed17800-e33c-11e8-8e09-3a2dcd76594a.png">

It takes up a second line, however, which is very wasteful in screen real estate.  Our apps tend to be dense and we want a compact depiction.

**Comment by kayiuho** [comment]
Hi Scott,

I've taken a look at this problem you are having and here's are some recommendations:

The Back+Next arrow icons could be more explicit on what they are intended to do when users click on them, so you're on the right track about displaying words instead of icons (example from the step pattern screen). I understand your concern over the "correct" placement of these 4 actions needed in the header and real estate on the page is valuable. I'm wondering about what "Cancel" does in this child page? If it takes the users back to the parent page which the back arrow on the far left does also, then the "cancel" could be eliminated to then only provide users with 3 actions on top – Approve (which is dynamic based on permission), Previous Project, Next Project). 

If Approve is the primary action on this page then I would stick with having this action to be a button (which you have currently). I would recommend then having "Previous Project" and "Next Project" to the right of the "Approve" button (where "cancel" sits currently) to avoid having actions to shuffle when Approve is not fixed. If it is possible, it could even be more explicit to give users more context of what the actions would take them exactly by having the names be dynamic, like Project 2, Project 4, etc... When there is a need of a "..." for more options, then it could sit on the right side of the same line so the placement of the actions would look something like this: Approve button, Project 3, Project 5, (...) 

You may also consider adding left and right caret icons (https://design.infor.com/code/ids-enterprise/latest/demo/icons/example-caret?font=source-sans) for "Previous Project" and "Next Project" if space allows. 

Also, while I was looking at the screens, I noticed some icons inconsistency where some actions (Review, Create) would have an icon next to them while other actions are icons only (like the icon next to "Applications" in the parent screen on the top header). Stand alone icons are usually only recommended in a couple scenarios – when space is limited or the icon has a universal meaning that is very easy to understand. When they are used alone, they can be difficult to interpret, especially for new users, so I would just keep that in mind for the future.

Let me know if you need any additional support.

**Comment by scott-newman-infor** [comment]
Hi and thanks for the feedback.

Regarding the "Cancel" button, that's a real server action in this case that would either change the state of the document or delete it depending on implementation.   So it's not the same as drill-back.

The sequence of "Approve button, Project 3, Project 5, (...)" has some difficulties:
1. By spelling out "Project 3" and "Project 5" the size of the buttons vary per page.  So they jump around.  That would not happen if we used icons alone or spelled the words as "Previous" and "Next".
2. Soho's toolbar doesn't actually allow us (to my knowledge) to place actions stably in place next to the "..." menu.  The placement of the buttons can change by resizing the screen, with buttons flowing into and out of the "..." menu based on screen real estate.  The first button in the toolbar is considered most primary while the last button would be the first to spill into the "..." menu.  So we'd have to "force" those buttons be present somehow if that's even possible.
3. As you know, the actions are often present based on permissions of the user and the state of the document.  That means, the actions for one document may differ from the previous and next ones.  And by extension, we'll possibly see the "..." menu appear and disappear.  That causes more jitter.

For all these reasons, maybe the previous/next buttons belong to the right of the "..." menu?  Separated by a "|" maybe?  That way it's always stable.  Unfortunately that makes them inconsistent in appearance to other toolbars on screen.

Caret icons sound good...I'll try that out.

Thanks for the feedback on icons without labels, which makes sense.  In the top-nav I'd say the Home icon is pretty universal but it's arguable whether that second "tasks" icons is.

I'd actually ask a related question to that top nav bar which maybe you were getting at.  Why do we not have icons for "Applications" "Tools" "Anayltics"?  Is that a bad practice to mix buttons with and without icons?  We see that throughout our system because developers don't usually have a unique icon per action.  Is it best to leave out icons completely if we don't have one for every button?

**Comment by kayiuho** [comment]
For the pairing of "Approve" and "Cancel", "Cancel" just feels like you can dismiss like what you'd see in modals. If "Cancel" actually holds more meaning behind, then I'd recommend using a term that's more explicit (like you mentioned, Delete) so users would know what to expect from the action.

1. I had a feeling that's the case where the terms need to be fixed, then I'd recommend going with "Previous" and "Next".
2. I see what you mean, hopefully you'll be able to make those stick. 
3. I understand, the only fixed actions here are "Previous" and "Next", and dynamic ones are (...), Approve, and Cancel.

I see your point.. so the toolbar could look like this: 
Approve  Cancel  (...)  |  < Previous   Next >

And regarding the icons, the second "tasks" icon was difficult for me to figure out (as I thought it was something to do with reporting). I think from a usability perspective, if there's no icon for that one particular action, it'd be better to have the words spelled verses having a unique icon that users would have to guess and possibly getting them to click on something that they didn't mean to. Is it better to leave out icons all together since some actions don't have icons? Not completely. I think it depends on the design and the use case. For the top-nav example, there are 3 types going on:  icon only, icon + text, text. Because there are no good icons available for "Applications" "Tools" "Anayltics", then one way to keep it clean and consistent is to keep the Home icon as is but use text only for the other 5 actions. On top of that, all icons should have a "pop over" to still offer context to the users.

**Comment by theakatz** [comment]
@scott-newman-infor hoping we were able to answer all of your questions. Going to go ahead and close this now. If you have any follow ups please feel free to reopen.

**Comment by scott-newman-infor** [comment]
Yes, thanks for your help. Here's how it looks:

<img width="832" alt="screen shot 2018-11-09 at 12 09 45 pm" src="https://user-images.githubusercontent.com/42583078/48418360-1bbc5880-e723-11e8-89e0-af614df81670.png">
