### ISSUE TITLE
Add dark and contrast variants for uplift theme

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#299]
- [x] Uplift dark variant
- [x] Uplift high-contrast variant

**Comment by tmcconechy** [comment]
One thing to note is once these two are finalized i'll need to add more to this PR so that they because available in the new Theme API. https://github.com/infor-design/enterprise/pull/1971

Do we have a token with all the available themes? At the moment I hard coded this in that API but if we had a way to list the themes that would make it easier to add more now if i pull from that.

**Comment by nickwynja** [comment]
@tmcconechy We don't currently. It might be helpful for cases like this to generate a `metadata.json` kind of like we do with icons.
