### ISSUE TITLE
[Support] Import Components to Lucidchart

### ISSUE THREAD

**Issue by asampogna** [infor-design/design-system#305]
Hello, I hope that you are well, I worked with the SoHo icons time ago and then I looked for them in the new library (Infor Design), I’m importing some icons that I need to Lucidchart, the ones that I extracted directly from SoHo looks good, but the ones that I extracted from the new library are invisible in the Shapes section and when I drag it they are in bold, and if I try to resize they don’t move as image, the width and height change… 

Please see an example below… the + icon is from the SoHo Library and the alert icon is from the Infor Design library… 

 
![example](https://user-images.githubusercontent.com/47124792/53190171-9c1a1180-35ce-11e9-85c7-4f73fe3a1ac8.jpg)

All the files are in SVG format, could you oriented me with this or can you let me know who can help me please?

Appreciate it…
Kind regards!

**Comment by asampogna** [comment]
Hello, I found most of the icons in the SoHo library, I only need the circle empty (radio button empty), I found it in the Infor Design Page ("empty-circle.svg") but I can't see it in the right format in Lucidchart, as per my comments in the first message...

![example](https://user-images.githubusercontent.com/47124792/53196990-e6a38a00-35de-11e9-9adf-67bb2536d185.JPG)

Appreciate your help with this...
Thanks and best regards!

**Comment by asampogna** [comment]
Hello, one last comment regarding the same, I need three more icons:

- Restore User
- Clear Search
- Stop

Additional to the Empty Circle mentioned above.

![restoreuser](https://user-images.githubusercontent.com/47124792/53201014-916c7600-35e8-11e9-9aae-49c9d57f3388.JPG)
![clearsearch](https://user-images.githubusercontent.com/47124792/53201015-916c7600-35e8-11e9-951e-8e3f31b6e6f6.JPG)
![stop](https://user-images.githubusercontent.com/47124792/53201016-916c7600-35e8-11e9-8076-565e6f506c1b.JPG)

Appreciate your help with those...
Thanks and best regards!

**Comment by nickwynja** [comment]
Hi @asampogna,

I've looked into the issue you're having where the icon is invisible in LucidChart and I think I understand what's going on. We've optimized the SVGs for use in web development which changes some of the default attributes of the SVG for better control through CSS. But I think this optimization, where we remove any default color on SVG shapes so colors can be set in CSS, is causing them to have no color in LucidChart.

I'll leave this ticket open and we'll consider how we could support this use case in LucidChart, since I know other people in the company use it for wireframes as well.

We've also just released a feature on the design system website to improve the experience of finding and downloading icons: https://design.infor.com/guidelines/identity/icons

In regards to your request for additional icons, we currently aren't adding to the icon set. Please use the best option you can find in the existing set of icons.

**Comment by asampogna** [comment]
Thanks Nick, the icon of Restore User is listed in the SoHo library, I can see the PNG file but the SVG image looks transparent: 
https://git.infor.com/projects/SOHO/repos/controls/browse/images/additional-icons/restore-user.png
https://git.infor.com/projects/SOHO/repos/controls/browse/images/additional-icons/restore-user.svg

Same case for the Zoom-in icon (maybe I use it for the Clear Search):
https://git.infor.com/projects/SOHO/repos/controls/browse/images/additional-icons/zoom-in.png
https://git.infor.com/projects/SOHO/repos/controls/browse/images/additional-icons/zoom-in.svg

Could you take a look and send me the SVG file visible if possible please?

Appreciate it...
Kind regards!

**Comment by nickwynja** [comment]
@asampogna I've added the "Extended Icon Set" to the https://design.infor.com/guidelines/identity/icons page. The "extended" set includes the `restore-user` and `zoom-in` icons. Please try to download these icons from https://design.infor.com/guidelines/identity/icons and see if that helps.

I wouldn't recommend using the `zoom` icons to clear search. The `close` icon, which is simply an `X` should work better for that case if you're able to use the clear icon with the field like this:

https://design.infor.com/code/ids-enterprise/latest/demo/components/input/example-clearable

(To see the `x` in the demo, you need to type something in the field.)

**Comment by asampogna** [comment]
I will use Close instead the zoom icons, thanks for the recommendation Nick...

Thank again for your support.
Best regards!
