### ISSUE TITLE
SVG Titles

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/design-system#356]
It looks like we're removing the "title" tag in our SVGs. Can we include them for better accessibility?

**Comment by tmcconechy** [comment]
Are you referring to these svg's ? http://master-enterprise.demo.design.infor.com/components/icons/example-index.html

If so what we usually do is include a screen reader label with the icon in a button so that its accessible as the label. Doing this is more consistent for some browsers handling svg.

```
<button type="button" class="btn-icon hide-focus" id="calendar-enabled">
            <span>Date</span>
            <svg role="presentation" aria-hidden="true" focusable="false" class="icon">
              <use xlink:href="#icon-calendar"></use>
            </svg>
          </button>
```
Maybe your talking about another aspect of it so if so ignore me.

**Comment by kentonquatman** [comment]
Oh, gotcha. That works! I'll mark this as closed.
I was just looking at one of the SVG files and noticed that we removed the title. I wondered if we needed it for screen readers, but it looks like we have another system in place for that.
Thanks!
