### ISSUE TITLE
Building new web apps 

### ISSUE THREAD

**Issue by maljiGit** [infor-design/design-system#360]
I am developing a new web application. For that I need to create new components with a different color theme. What is the procedure to create a new web application?

**Comment by nickwynja** [comment]
Hi @maljiGit. For getting started with the components in a web application, I'd recommend checking out our [developer guide](https://github.com/infor-design/enterprise/blob/master/docs/DEVELOPER.md) and the [component documentation](https://design.infor.com/code/ids-enterprise/latest) for the Enterprise components.

I'd also suggest looking into our [Angular component wrappers](https://github.com/infor-design/enterprise-ng) and the [Angular quickstart](https://github.com/infor-design/enterprise-ng-quickstart) repository, since we recommend people using Angular for their web applications.

If you have more specific questions in regards to the Enterprise component library or Angular wrappers, I'd recommend opening a support ticket in their respective repositories.

Thanks,
Nick
