### ISSUE TITLE
Uplift Icons Need some Further Tweaks

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/design-system#364]
**Describe the bug**
When reviewing the page 
https://master-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=uplift which uses the new sketch file icons and generation process some icons need a bit of work.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=uplift 
2. Look at the icons and identify irregularities 

**Issues List**

- [x] The sizes all seem smaller than https://master-enterprise.demo.design.infor.com/components/icons/example-index.html is the base size correct?
- [x] The two alert icons and icons that are filled vs not filled are different sizes.
![Screen Shot 2019-04-09 at 3 07 15 PM](https://user-images.githubusercontent.com/814283/55828309-244e6a80-5ada-11e9-9571-1528c2f92d01.png)
- [x] Some icons that have the bottom edge cut out by the design do not seem to make sense. For example the home icon (second one)
![Screen Shot 2019-04-09 at 3 07 43 PM](https://user-images.githubusercontent.com/814283/55828360-3c25ee80-5ada-11e9-9ee6-9f99cee58bbd.png)
- [x] And the component icon (second one)
![Screen Shot 2019-04-09 at 3 08 16 PM](https://user-images.githubusercontent.com/814283/55828372-421bcf80-5ada-11e9-99b4-ad8427631a1a.png)
- [x] In the extended icons section the PDF, TXT (Filename) icons are all a bit bigger
- [ ] In the editor section some icons are a lot smaller than each other (the text ones in particular) see the out put on https://github.com/infor-design/enterprise/issues/1937 perhaps they need tweaking to fit there better?
- [x] The ... icon on the top of the page and in the set seems a little small?

**Platform**
- Chrome / mac

**Comment by nickwynja** [comment]
The ones marked ☑️  above have been addressed within source file updates. I think the rest need to be handled within Enterprise.

I agree with you that they appear smaller in the uplift set. I know that we've used the same 18x18 artboard frame for this set but some uplifted icons might be a bit smaller within the artboard. This could be in part to keep the icon design on the pixel grid to ensure crispness. Maybe @kayiuho and @elizabethhartley can help clarify what's happening here. For example, `launch` looks to be similar between the two sets but `alert` in Uplift is much smaller than it's counterpart in Soho. I'm not sure whether we need to bump up the baseline icon size within Enterprise Uplift CSS versus within the artboard design itself.

**Comment by kayiuho** [comment]
We can definitely take a second look at the sizing of them, especially the unchecked ones that are mentioned above. The artboard is still 18x18 but I think the padding around the icon itself is bigger than the Soho set.

**Comment by kayiuho** [comment]
The main difference from the design ops perspective is that icons in the uplift set are placed in the artboard with a larger padding. The `Calendar` icon demonstrate this well: 
![icon_soho_uplift_cal](https://user-images.githubusercontent.com/34747859/56911974-435a6f80-6a7c-11e9-9317-e446d1c325d4.png)
**Q**: Do we want to resize all Uplift icons, so that they touch the edges, making the max length as close to 18px as possible for consistency sake? 

Same point applies to the `html editor` icons. But also, there's custom css that's built into the component that were meant to be used with the Soho icons. Not sure if there's another way to go around it without changing the codes and causing things to break when we switch themes? I also posted this in https://github.com/infor-design/enterprise/issues/1937 

As for the files icons, they are not "bigger" as the others are just smaller in comparison. The output size in the demo site isn't the same as the artboard size.
**Soho**: artboards - 13x14, demo site - 16.71x18
**Uplift**: artboards - 14x14, demo site - 18x16.71
<img width="1054" alt="icons_file_soho" src="https://user-images.githubusercontent.com/34747859/56913770-7dc60b80-6a80-11e9-8fbe-53e36bb7b400.png">
<img width="1124" alt="icons_file_uplift" src="https://user-images.githubusercontent.com/34747859/56913781-81f22900-6a80-11e9-99ee-8f52845455b2.png">
**Q**: Do we want to change the Uplift artboard for `Files` to be 18x18 for consistency sake?

**Comment by nickwynja** [comment]
> Q: Do we want to resize all Uplift icons, so that they touch the edges, making the max length as close to 18px as possible for consistency sake?

I think we need to consider what effect this will have on aligning with the pixel grid and ability to center elements within the shape. In general, up-scaling the icons within CSS will mess with the pixel-perfectness so it's likely better to handle this within the design asset.

> Q: Do we want to change the Uplift artboard for Files to be 18x18 for consistency sake?

I believe there's a reason why they are currently 14x14. Maybe for better support in the tree? It could be that they're just displayed "incorrectly" on this example page but fit better in their tree example. We could possible add a `demo-icon-tree` class or something which would bump the size of the example icon down to the size it is in the tree component.

**Comment by tmcconechy** [comment]
Yeah "better support for tree" is accurate. The thing with the tree is it can have a lot of nodes, so people like the lines to be compact, so the smaller icon was used. A big change there in size would really reduce the number of visible nodes. So probably would want to keep a smaller size there.

**Comment by nickwynja** [comment]
Is the tree the primary use case for these file type icons? Another option could be to update the icon design to 18x18 (if they're used in other places) and then scale down the icon to 14x14 in CSS for the tree.

**Comment by tmcconechy** [comment]
The icon types where made as part of the tree design. But we later found out teams requesting to use the standalone (not in the tree). So i think ideally they should work in both places. So maybe have them at the normal size and size them down with css when in the tree?

**Comment by kayiuho** [comment]
Okay - so it sounds like we can change the artboard size for tree icons from 14x14 to 18x18 (like the rest) in the Sketch file, and we'll use a class for when those icons are used in the tree - yea?

> I think we need to consider what effect this will have on aligning with the pixel grid and ability to center elements within the shape. In general, up-scaling the icons within CSS will mess with the pixel-perfectness so it's likely better to handle this within the design asset.

We can scale them up carefully in Sketch to make sure the icons will still align to the grid and center elements within the shapes.
