### ISSUE TITLE
Fix-Revisit application menu hierarchy for clarity

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/design-system#409]
When a user expands a section in the application menu, it's difficult to tell which items belong in a section. In Uplift, there is no background color change for the grouping as in SoHo 4. Need a clearer way to show which level/group menu items belong 

Tooltip issue as well--displays with black text

![image](https://user-images.githubusercontent.com/44705854/64198480-e87fbd00-ce4d-11e9-8de9-81c249162cda.png)

**Comment by tmcconechy** [comment]
In IDS the corresponding examples are:

http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html?theme=uplift&variant=light&colors=0563C2
vs
http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html

**Comment by kevinwhitedesign** [comment]
After a brief look it seems that implementation may be a bit off on both sides of the spectrum here, and that this problem was starting to get solved in the design but not communicated well. I’ll try to resolve here. 

It seems that largely: alignment, vertical & horizontal spacing may be off in both LMK & IDS examples. The biggest problem in that is the vertical spacing and the lack of alignment in LVL 1 menu items. 

![IDS_ApplicationMenu_superExpandedNavItems_alt](https://user-images.githubusercontent.com/6478704/64361878-7210c580-cfdb-11e9-9a58-43c15c241241.png)
![IDS_ApplicationMenu_superExpandedNavItems](https://user-images.githubusercontent.com/6478704/64361879-72a95c00-cfdb-11e9-9141-4456dfa92904.png)
![IDS_ApplicationMenu_expandedNavItems](https://user-images.githubusercontent.com/6478704/64361880-72a95c00-cfdb-11e9-8811-78ab75360878.png)
![IDS_ApplicationMenu_WithoutIcons](https://user-images.githubusercontent.com/6478704/64361881-72a95c00-cfdb-11e9-9000-bd6bfd522489.png)
![IDS_ApplicationMenu_WithIcons](https://user-images.githubusercontent.com/6478704/64361882-72a95c00-cfdb-11e9-87c0-f7f901c471d8.png)






Approx. Adjustment Log:

- Even distribution of HCM nav icons at the top. 
- Search bar hint text should more clearly tell the user what they can do. If this was a full HCM search then the text ‘search’ would work. However, since it’s nav items and sub pages it doesn’t seem appropriate or helpful. Push it further: an additional idea here is to have the user click in and then immediately get suggestions on what to search for, or things they’ve searched for in the past. For the interim, “Look up menu items” feels very appropriate to me.
- Comfy-er search bar in general. Is consistent with selection / hover states for menu items as well. (40px H, 288 W, 6px Radius)
- Some additional space between header & menu items. Visual separation. (40px vert)
- Clear difference in padding on the left for menus with icons and without.
- For this menu example, active menu items take on the selected UI theme (instead of the azure). This is basically for theme consistency so that if this was the slate theme or the azure theme, we’d be using values from those families.
- LVL1 Selected menu item is
    - Text: bold, #fff @ 100% opacity
    - Bg: #fff @ 15% opacity
- LVL1 Hover menu item is
    - Text: Reg, #fff @ 100%
    - Bg: #fff @ 5%
- Vertical spacing between selected & hover states is 4px
- Update chevron icon to Uplift style
- LVL1 Selected expanded menu item
    - Text: Bold, #fff @ 100%
    - Bg: #000 @ 20% Opacity
    - Chevron: #fff @ 100%
- Use uplift chevron icons
- Use uplift add / minus icons
- Expanded LVL1 sections have additional vertical spacing at bottom (56px)
- LVL2-6 Normal state menu item 
    - Text: Regular, 14px, #fff @ 50% opacity
    - Icon: #fff @ 50% opacity
- LVL2-6 Selected / Hover menu item
    - Text: Reg, 14px #fff @ 100%
    - Bg: #fff @ 15%

Provided an alternative for a background, although text indentation, lvl 1 expansion and text styling should solve for this issue sufficiently.

https://inforus.invisionapp.com/share/QZTSFWVAFS2

**Comment by tmcconechy** [comment]
This seems done so closing we are working to add it to the code base on https://github.com/infor-design/enterprise/issues/2739
